package com.training.enums;

public enum SecurityEventType {
    SCREEN_RECORDING_ATTEMPT,
    SCREENSHOT_ATTEMPT,
    SCREEN_SHARE_STARTED,
    SCREEN_SHARE_STOPPED,
    SCREEN_SHARE_INTERRUPTED,
    SUSPICIOUS_CAPTURE_ACTIVITY,
    PROTECTION_ACTIVATED,
    TAB_HIDDEN,
    TAB_VISIBLE,
    WINDOW_BLUR,
    WINDOW_FOCUS,
    FULLSCREEN_EXITED,
    MULTIPLE_SESSION_DETECTED,
    SESSION_TERMINATED,
    SUSPICIOUS_ACTIVITY
}
